/*
 * Example: STM32 HAL + Rotary Encoder E38S6G5-600B-G24N
 *
 * Hardware example mapping (STM32F1):
 *   Encoder A -> PA0 (TIM2_CH1)
 *   Encoder B -> PA1 (TIM2_CH2)
 *
 * Notes:
 * - Ensure signal voltage is safe for MCU GPIO (typically 3.3V).
 * - For open-collector output, use pull-up to 3.3V.
 */

#include "main.h"
#include <math.h>

TIM_HandleTypeDef htim2;

#define ENCODER_PPR     600.0f
#define QUAD_FACTOR     4.0f
#define CPR_X4          (ENCODER_PPR * QUAD_FACTOR)   // 2400 counts/rev
#define SAMPLE_MS       10.0f                         // speed update period

volatile int32_t g_position_counts = 0;
volatile float g_rpm = 0.0f;

static int16_t prev_cnt16 = 0;

static void SystemClock_Config(void);
static void MX_GPIO_Init(void);
static void MX_TIM2_Init_Encoder(void);
static void Encoder_Update(void);

int main(void)
{
  HAL_Init();
  SystemClock_Config();
  MX_GPIO_Init();
  MX_TIM2_Init_Encoder();

  HAL_TIM_Encoder_Start(&htim2, TIM_CHANNEL_ALL);

  prev_cnt16 = (int16_t)__HAL_TIM_GET_COUNTER(&htim2);

  uint32_t last_tick = HAL_GetTick();

  while (1)
  {
    uint32_t now = HAL_GetTick();
    if ((now - last_tick) >= (uint32_t)SAMPLE_MS)
    {
      last_tick = now;
      Encoder_Update();

      // Example: convert absolute position to angle in [0, 360)
      float mechanical_revs = (float)g_position_counts / CPR_X4;
      float angle_deg = fmodf(mechanical_revs * 360.0f, 360.0f);
      if (angle_deg < 0.0f) angle_deg += 360.0f;

      // place breakpoint or print via UART:
      // printf("cnt=%ld angle=%.2f rpm=%.2f\r\n", g_position_counts, angle_deg, g_rpm);
      (void)angle_deg;
    }
  }
}

static void Encoder_Update(void)
{
  int16_t cnt16 = (int16_t)__HAL_TIM_GET_COUNTER(&htim2);

  // Signed delta handles timer overflow/underflow naturally in int16_t space
  int16_t delta = (int16_t)(cnt16 - prev_cnt16);
  prev_cnt16 = cnt16;

  g_position_counts += delta;

  // RPM = (delta_counts / CPR) / (sample_time_min)
  // sample_time_min = SAMPLE_MS / 60000
  g_rpm = ((float)delta / CPR_X4) * (60000.0f / SAMPLE_MS);
}

static void MX_TIM2_Init_Encoder(void)
{
  TIM_Encoder_InitTypeDef sConfig = {0};
  TIM_MasterConfigTypeDef sMasterConfig = {0};

  htim2.Instance = TIM2;
  htim2.Init.Prescaler = 0;
  htim2.Init.CounterMode = TIM_COUNTERMODE_UP;
  htim2.Init.Period = 0xFFFF;
  htim2.Init.ClockDivision = TIM_CLOCKDIVISION_DIV1;
  htim2.Init.AutoReloadPreload = TIM_AUTORELOAD_PRELOAD_DISABLE;

  sConfig.EncoderMode = TIM_ENCODERMODE_TI12;
  sConfig.IC1Polarity = TIM_ICPOLARITY_RISING;
  sConfig.IC1Selection = TIM_ICSELECTION_DIRECTTI;
  sConfig.IC1Prescaler = TIM_ICPSC_DIV1;
  sConfig.IC1Filter = 6; // small digital filter for noise

  sConfig.IC2Polarity = TIM_ICPOLARITY_RISING;
  sConfig.IC2Selection = TIM_ICSELECTION_DIRECTTI;
  sConfig.IC2Prescaler = TIM_ICPSC_DIV1;
  sConfig.IC2Filter = 6;

  if (HAL_TIM_Encoder_Init(&htim2, &sConfig) != HAL_OK)
  {
    Error_Handler();
  }

  sMasterConfig.MasterOutputTrigger = TIM_TRGO_RESET;
  sMasterConfig.MasterSlaveMode = TIM_MASTERSLAVEMODE_DISABLE;
  if (HAL_TIMEx_MasterConfigSynchronization(&htim2, &sMasterConfig) != HAL_OK)
  {
    Error_Handler();
  }
}

static void MX_GPIO_Init(void)
{
  __HAL_RCC_GPIOA_CLK_ENABLE();

  GPIO_InitTypeDef GPIO_InitStruct = {0};

  // TIM2_CH1 (PA0), TIM2_CH2 (PA1)
  GPIO_InitStruct.Pin = GPIO_PIN_0 | GPIO_PIN_1;
  GPIO_InitStruct.Mode = GPIO_MODE_INPUT;
  GPIO_InitStruct.Pull = GPIO_PULLUP; // for open-collector case, or use external pull-up
  HAL_GPIO_Init(GPIOA, &GPIO_InitStruct);
}

static void SystemClock_Config(void)
{
  // Configure according to your project/board generated by CubeMX.
}

void Error_Handler(void)
{
  __disable_irq();
  while (1) {}
}
